services:
  postgres:
    env_file:
      - .env
    image: "postgres"
    ports:
      - "${DB_HOST_PORT}:${DB_IMAGE_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    env_file:
      - .env
    build:
      context: .
      target: production
      args:
        - APP_IMAGE_PORT=${APP_IMAGE_PORT}
        - DB_HOST_PORT=${DB_HOST_PORT}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${APP_HOST_PORT}:${APP_IMAGE_PORT}"
    depends_on:
      - postgres
